config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers, shallow: true do
      post :mark_best, on: :member
    end
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true

  scope :sort_by_best, -> { order best: :desc }

  def mark_best
    other_best_answer = question.answers.where(best: true).first
    transaction do
      other_best_answer&.update!(best: false)
      update!(best: !best)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, :body, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  def author?(object)
    self.id == object.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  expose :answer
  expose :question, -> { Question.find(params[:question_id]) }

  def create
    @exposed_answer = question.answers.create(answer_params.merge( user_id: current_user.id))
  end

  def update
    answer.update(answer_params) if current_user.author?(answer)
    @exposed_question = answer.question
  end

  def destroy
    answer.destroy if current_user.author?(answer)
  end

  def mark_best
    answer.mark_best if current_user.author?(answer.question)
    @exposed_question = answer.question
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  expose :questions, -> { Question.all }
  expose :question
  expose :answer, -> { Answer.new }

  def create
    @exposed_question = current_user.questions.new(question_params)

    if question.save
      redirect_to question_path(question), notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params) if current_user.author?(question)
  end

  def destroy
    if current_user.author?(question)
      question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted.'
    else
      redirect_to questions_path, notice: 'You have no rigths to delete this question.'
    end
  end


  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
div id = "answer_#{answer.id}"
  -if answer.best
    | Best answer!
  p= answer.body
  - if current_user&.author?(answer)
    p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    p= link_to 'Delete answer', answer_path(answer), remote: true,
      method: :delete

  - if current_user&.author?(question) && !answer&.best
    = link_to 'Best answer', mark_best_answer_path(answer), method: :post, remote: true

  = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}"} do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    = f.submit 'Save'

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: answer
= form_with model: [ question, answer ], class: 'new-answer' do |f|
  = f.label :body
  = f.text_area :body
  = f.submit 'Reply'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% if answer.persisted? %>
  $('.answers').append('<%= j render answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer_<%= answer.id %>').remove();

app/views/answers/mark_best.js.erb
$('.answer-errors').html("<%= j render 'shared/errors', resource: answer %>");

<% unless answer.errors.present? %>
  $('.answers').html("<%= j render question.answers.sort_by_best %>");
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% unless answer.errors.present? %>
  $('#answer_'+ <%= answer.id %>).replaceWith('<%= j render answer %>');
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title QnA
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    nav
    - if user_signed_in?
      = link_to 'Log Out', destroy_user_session_path, method: :delete
    - else
      = link_to 'Sing In', new_user_session_path
      = link_to 'Sign Up', new_user_registration_path

    p.notice = notice
    p.alert = alert
    = yield

app/views/questions/_question.html.slim
div id = "question_#{question.id}"
  tr
    td= question.title
    td= question.body
    td= link_to 'Show', question_path(question)
    - if current_user&.author?(question)
      td= link_to 'Edit', '#', class: 'edit-question-link', data: {question_id: question.id}
      td= link_to 'Delete', question, method: :delete

  = form_with model: question, class: 'hidden', html: {id: "edit-question-#{question.id}"} do |f|
    = f.label :title, 'Your question'
    = f.text_field :title
    = f.label :body
    = f.text_area :body
    = f.submit 'Save'

app/views/questions/index.html.slim
h1 Questions list


.question-errors

.questions
  = render questions

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Ask'

app/views/questions/show.html.slim
h1= question.title
p= question.body
- if current_user&.author?(question)
  = link_to 'Delete', question_path(question),
    method: :delete,
    data: { confirm: 'Are you sure?' }

.answers
  = render question.answers.sort_by_best

h2 Add an answers
= render 'answers/form'

br
  = link_to 'Back', questions_path

app/views/questions/update.js.erb
$('.question-errors').html("<%= j render 'shared/errors', resource: question %>");

<% unless question.errors.present? %>
  $('#question_'+ <%= question.id %>).replaceWith("<%= j render question %>");
<% end %>

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message